# Generated by Django 3.2 on 2021-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='PokeDex index number')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Pokemon')),
                ('type1', models.CharField(max_length=50, verbose_name='Type of Pokemon')),
                ('type2', models.CharField(max_length=50, verbose_name='Other Type of Pokemon')),
                ('hp', models.IntegerField(verbose_name='Hit Points')),
                ('attack', models.IntegerField(verbose_name='Attack Strength')),
                ('defense', models.IntegerField(verbose_name='Defensive Strength')),
                ('sp_atk', models.IntegerField(verbose_name='Special Attack Strength')),
                ('sp_def', models.IntegerField(verbose_name='Special Defensive Strength')),
                ('speed', models.IntegerField(verbose_name='Speed')),
                ('generation', models.IntegerField(verbose_name='Generation')),
                ('legendary', models.BooleanField(default=False, verbose_name='Legendary Pokemon?')),
            ],
            options={
                'ordering': ('number', 'name'),
            },
        ),
    ]
