# Generated by Django 3.2 on 2021-06-21 12:10

from django.db import migrations
from django.conf import settings

import os
import csv

NUMBER = 0
NAME = 1
TYPE1 = 2
TYPE2 = 3
HP = 4
ATTACK = 5
DEFENSE = 6
SP_ATK = 7
SP_DEF = 8
SPEED = 9
GENERATION = 10
LEGENDARY = 11


def load_pokemon_data(apps, schema_editor):
    Pokemon = apps.get_model('app', 'Pokemon')

    file_name = os.path.join(settings.DATA_DIR, 'pokemon.csv')
    with open(file_name, newline='') as csvfile:
        pokemon_reader = csv.reader(csvfile, delimiter=',')
        next(pokemon_reader)  # skip first row
        for row in pokemon_reader:
            Pokemon.objects.create(
                number=row[NUMBER],
                name=row[NAME],
                type1=row[TYPE1],
                type2=row[TYPE2],
                hp=row[HP],
                attack=row[ATTACK],
                defense=row[DEFENSE],
                sp_atk=row[SP_ATK],
                sp_def=row[SP_DEF],
                speed=row[SPEED],
                generation=row[GENERATION],
                legendary=True if row[LEGENDARY] == 'TRUE' else False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_pokemon_data, reverse_code=migrations.RunPython.noop),
    ]
